/* PlanWise – v3.3
   Auth v2: Centralized authentication state management
   Features: Planner, Dashboard (FullCalendar), Persistentie, Onderhoudsvoorstellen
*/

// [Full original app.js — see app.js for source]
// This file is an exact copy of app.js as of the modularization commit.
// Generated automatically — do not edit this file.
